language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

after_success:
  - git clone --depth 1 https://github.com/urho3d/emscripten-sdk.git
  - pushd emscripten-sdk
  - ./emsdk update
  - ./emsdk install sdk-incoming-64bit
  - source ./emsdk_env.sh
  - popd
  - mkdir .cargo
  - echo "[target.asmjs-unknown-emscripten]linker=\"./emcc-sdl\"" >> .cargo/config
  - echo "emcc -s USE_SDL=2 -s USE_SDL_TTF=2 $@" >> emcc-sdl
  - chmod u+x ./emcc-sdl
  - rustup target add asmjs-unknown-emscripten
  - ./deploy.sh

cache:
  cargo: true
  directories:
  - emsdk-portable
