addons:
  ssh_known_hosts: ael.red
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-ttf-dev

language: rust

rust:
- nightly
- beta
- stable

matrix:
  allow_failures:
  - rust: nightly

dist: trusty

before_install:
  - openssl aes-256-cbc -K $encrypted_c494ad7d7799_key -iv $encrypted_c494ad7d7799_iv -in deploy_key.enc -out deploy_key -d

after_success:
  - chmod 600 ./deploy-key
  - mv ./deploy-key ~/.ssh/id_rsa
  - ls
  - ssh felix@ael.red -s "bash -s" < ./deploy.sh

cache:
  cargo: true
