language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

after_success:
  - git clone --depth 1 https://github.com/urho3d/emscripten-sdk.git -b incoming
  - pushd emscripten-sdk
  - ./emsdk activate sdk-incoming-64bit
  - source ./emsdk_env.sh
  - popd
  - rustup target add asmjs-unknown-emscripten
  - ./deploy.sh

cache:
  cargo: true
  directories:
  - emsdk-portable
