addons:
  ssh_known_hosts: ael.red
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev

language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

dist: trusty

after_success:
  - ssh felix@ael.red -s "bash -s" < ./deploy.sh

cache:
  cargo: true
