language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
