addons:
  ssh_known_hosts: ael.red
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-ttf-dev

language: rust

rust:
- nightly
- beta
- stable

matrix:
  allow_failures:
  - rust: nightly
jobs:
  include:
    - stage: deploy
      rust: stable
      script: deploy/travis-deploy.sh

dist: trusty
sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_c494ad7d7799_key -iv $encrypted_c494ad7d7799_iv -in deploy/deploy_key.enc -out deploy_key -d

cache:
  cargo: true
