[package]
name = "tetris"
version = "0.1.0"
authors = ["Felix Chapman <aelred717@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3"
lazy_static = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.4"
hyper = "0.10.5"

[dev-dependencies]
quickcheck = "0.3"
