name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
  
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build server
        run: cd tetris-server && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tetris-server
          path: target/release/tetris-server

  deploy-server:
    runs-on: ubuntu-latest
    needs: [test, build-server]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tetris-server
      - name: Mark executable
        run: chmod u+x tetris-server
      - name: Deploy server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: tetris-server
          target: /opt/tetris/bin

  build-wasm-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v6
      - name: Add wasm target
        run: rustup target add wasm32-unknown-emscripten
      - name: Build wasm client
        run: cd tetris-sdl && cargo build --release --target wasm32-unknown-emscripten
      - name: Move wasm and js to static folder
        run: |
          mv target/wasm32-unknown-emscripten/release/tetris_sdl.wasm static/
          mv target/wasm32-unknown-emscripten/release/tetris-sdl.js static/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tetris-sdl-wasm
          path: static/

  deploy-wasm-client-to-server:
    runs-on: ubuntu-latest
    needs: [test, build-wasm-client]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tetris-sdl-wasm
          path: tetris-sdl-wasm
      - name: Deploy wasm client
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: tetris-sdl-wasm/*
          target: /var/www/tetris.${{ secrets.HOST }}
          strip_components: 1

  deploy-wasm-client-to-s3:
    runs-on: ubuntu-latest
    needs: [test, build-wasm-client]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tetris-sdl-wasm
          path: tetris-sdl-wasm
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy wasm client to S3
        run: aws s3 cp tetris-sdl-wasm s3://${{ secrets.WASM_CLIENT_BUCKET }}/ --recursive
