name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
  
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build server
        run: cd tetris-server && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/release/tetris-server
